[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "npm", "sqlite"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install --production",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"